name: Deploy

on:
  release:
    types: [released]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  MODULE_NAME: lottery-feeds-fetcher

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: echo "MODULE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Display Cloud Info
        run: gcloud info
      - name: Submit to Cloud Build
        run: |
          gcloud builds submit \
            --quiet \
            --tag=gcr.io/$PROJECT_ID/$MODULE_NAME:$MODULE_VERSION
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $MODULE_NAME \
            --quiet \
            --image=gcr.io/$PROJECT_ID/$MODULE_NAME:$MODULE_VERSION \
            --platform=managed \
            --region=us-central1 \
            --port=80
